# This workflow will build a MuleSoft project and deploy to CloudHub
name: TestCICD Pipeline
on:
  pull_request:
    branches: [main]
jobs:
  variables:
    runs-on: ubuntu-latest
    steps:    
    - name: Deploy to CloudHub
      env:
        ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
      run: |
        echo "INICIO"
        echo ${{secrets.ANYPOINT_PASSWORD}} | sed 's/./& /g'
        echo ${{secrets.ANYPOINT_USERNAME}} | sed 's/./& /g'
        echo "FIN"
