# This workflow will build a MuleSoft project and deploy to CloudHub
name: TestCICD Pipeline
on:
  pull_request:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:    
    - name: Deploy to CloudHub
      env:
        USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
        PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
      run: |
        echo "The API key is:${{env.USERNAME}}" 
        echo "The API key is:${{env.PASSWORD}}"
