# This workflow will build a MuleSoft project and deploy to CloudHub
name: TestCICD Pipeline
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:    

    - name: Deploy to CloudHub
      env:
        USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
        PASSWORD: MuleSoft_spain_5
      run: |
        echo "PASS: $PASSWORD"
        echo "PASS3: ${{ secrets.ANYPOINT_USERNAME }}"
